tap "fsouza/prettierd"
tap "homebrew/bundle"
brew "docker"
brew "docker-compose"
brew "fd"
brew "gh"
brew "git"
brew "icu4c@77", link: true
brew "jq"
brew "libpq", link: true
brew "mise"
brew "tree-sitter"
brew "neovim"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
cask "1password"
cask "ghostty", args: { appdir: "/Applications" }
cask "git-credential-manager"
cask "monodraw"
cask "orbstack"
cask "steam"
cask "zed"
