# Taps
tap "homebrew/bundle"

# CLI Tools
brew "fd"
brew "gh"
brew "git"
brew "jq"
brew "mise"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "uv"

# GUI Applications
cask "1password"
cask "git-credential-manager"
cask "steam"
cask "zed"
