#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

echo "› brew bundle"
cd ./homebrew
brew bundle
cd "$(dirname $0)"/..
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done