return {
	"folke/which-key.nvim",
	event = "VimEnter",
	opts = {
		delay = 0,
		icons = {
			mappings = vim.g.have_nerd_font,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},
		spec = {
			{ "<leader>f", group = "Find" },
			{ "<leader>g", group = "Git" },
			{ "<leader>m", group = "Markdown" },
			{ "<leader>s", group = "Search/Replace" },

			{ "]d", desc = "Next diagnostic" },
			{ "[d", desc = "Previous diagnostic" },
			{ "]c", desc = "Next git change" },
			{ "[c", desc = "Previous git change" },
			{ "]q", desc = "Next quickfix" },
			{ "[q", desc = "Previous quickfix" },

			{ "<leader>x", desc = "Close buffer" },
			{ "<leader>q", desc = "Close window" },
			{ "<leader>o", desc = "Only this window" },
			{ "<leader>d", desc = "Diagnostics panel" },
			{ "<leader>e", desc = "File explorer" },
			{ "<leader>r", desc = "Rename" },
			{ "<leader>a", desc = "Code action" },
			{ "<leader>F", desc = "Format" },
			{ "<leader>D", desc = "Delete to register" },

			{ "K", desc = "Hover documentation" },
			{ "gd", desc = "Go to definition" },
			{ "gr", desc = "References" },

			{ "<C-h>", desc = "Move to left window" },
			{ "<C-l>", desc = "Move to right window" },
			{ "<C-j>", desc = "Move to lower window" },
			{ "<C-k>", desc = "Move to upper window" },

			{ "<Esc>", desc = "Clear search highlights", mode = "n" },
		},
	},
	keys = {
		{
			"<leader>?",
			function()
				require("which-key").show({ global = false })
			end,
			desc = "Buffer keymaps",
		},
	},
}
